name: WhatsApp Automation

on:
  
  workflow_dispatch:      # for manual test

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run WhatsApp bot
        run: npm start

      - name: Commit session, dashboard & aggregate
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # commit only necessary files
          git add session dashboard aggregate.json
          git commit -m "update session, dashboard & aggregate $(date +%F)" || echo "No changes"
          git push
